source 'https://rubygems.org'

gem 'mysql2'
gem 'thin'
gem 'sinatra', '~> 1.4.5'
gem 'sinatra-activerecord'
gem 'async_sinatra'
gem 'money'
gem 'possibly', '~> 0.2.0'
gem 'paypal-sdk-permissions', '~> 1.96.4'
gem 'paypal-sdk-merchant', '~> 1.116.0'
